-- Script 1
SELECT SURNAME || ', ' || FIRSTNAME
	FROM 	FACULTY
	WHERE	EMPLOYEE_ID IN (
		SELECT EMPLOYEE_ID
			FROM EXPERTISE
			WHERE EXPERTISE_LEVEL > 7
	)
	GROUP BY SURNAME, FIRSTNAME
	ORDER BY SURNAME;
-- Script 2
SELECT COURSE_TITLE
	FROM	COURSE
	WHERE	COURSE_CODE IN (
		SELECT 	COURSE_CODE
		FROM 	EXPERTISE
		WHERE 	EMPLOYEE_ID = (
			SELECT 	EMPLOYEE_ID
			FROM 	FACULTY
			WHERE	SURNAME 	= 'James'
			AND 	FIRSTNAME 	= 'Clifford'
		)
	);
-- Script 3
SELECT COURSE_TITLE
	FROM 	COURSE
	WHERE 	COURSE_CODE IN (
		SELECT	COURSE_CODE
		FROM	CLASS_SECTION
		WHERE	INSTRUCTOR_ID = (
			SELECT 	EMPLOYEE_ID
			FROM 	FACULTY
			WHERE	SURNAME 	= 'Curie'
			AND		FIRSTNAME 	= 'Marie'
		)
	);
-- Script 4
SELECT COUNT(*) AS "Students with No Grade"
	FROM COURSE_REGISTRATION
	WHERE GRADE IS NULL;	
-- Script 5
SELECT COURSE_TITLE
	FROM COURSE
	WHERE COURSE_CODE IN (
		SELECT COURSE_CODE
		FROM CLASS_SECTION
		GROUP BY COURSE_CODE
		HAVING COUNT(DISTINCT INSTRUCTOR_ID) >= 3
	)
	ORDER BY COURSE_TITLE;
-- Script 6
SELECT SURNAME || ', ' || FIRSTNAME AS "Faculty Name", SALARY AS "Salary"
	FROM FACULTY
	WHERE EMPLOYEE_ID NOT IN (
		SELECT EMPLOYEE_ID
		FROM EXPERTISE	
	)
	ORDER BY SURNAME;
-- Script 7
SELECT STUDENT_ID, COURSE_CODE
FROM COURSE_REGISTRATION
WHERE (COURSE_CODE, GRADE) IN (
	SELECT COURSE_CODE, MAX(GRADE)
	FROM COURSE_REGISTRATION
	WHERE GRADE IS NOT NULL
	GROUP BY COURSE_CODE
)
ORDER BY COURSE_CODE;
-- Script 8
SELECT STUDENT_ID, COURSE_CODE
FROM COURSE_REGISTRATION CRI
WHERE GRADE = (
	SELECT MAX(GRADE)
	FROM COURSE_REGISTRATION CRII
	WHERE CRII.COURSE_CODE = CRI.COURSE_CODE
	AND GRADE IS NOT NULL
)
AND GRADE IS NOT NULL
ORDER BY COURSE_CODE;
