-- Script 1
SELECT		SURNAME,	FIRSTNAME
	FROM	FACULTY		NATURAL	JOIN	EXPERTISE
   WHERE	EXPERTISE_LEVEL	> 7
   ORDER BY SURNAME;

-- Script 2
SELECT		SURNAME,	FIRSTNAME
	FROM 	FACULTY		
	JOIN	EXPERTISE	USING	(EMPLOYEE_ID)
   WHERE	EXPERTISE_LEVEL > 7
   ORDER BY SURNAME;

-- Script 3
SELECT		SURNAME,	FIRSTNAME
    FROM	FACULTY		f
	JOIN	EXPERTISE 	e
	  ON	(f.EMPLOYEE_ID = e.EMPLOYEE_ID)
   WHERE	EXPERTISE_LEVEL > 7
   ORDER BY	SURNAME;

-- Script 4
SELECT		SURNAME,	FIRSTNAME
	FROM	FACULTY	f,	EXPERTISE e
   WHERE	f.EMPLOYEE_ID = e.EMPLOYEE_ID
	 AND	e.EXPERTISE_LEVEL > 7
   ORDER BY	SURNAME;
	
-- Scrip 5
SELECT		COURSE_TITLE
	FROM	COURSE c
	JOIN	CLASS_SECTION cs
	  ON	(c.COURSE_CODE = cs.COURSE_CODE)
    JOIN	FACULTY f
	  ON	(cs.INSTRUCTOR_ID = f.EMPLOYEE_ID)
   WHERE	f.FIRSTNAME = 'Clifford'
	 AND	f.SURNAME	= 'James';

-- Script 6
SELECT		COURSE_TITLE
	FROM	COURSE c
	JOIN	CLASS_SECTION cs	ON (c.COURSE_CODE 		= 	cs.COURSE_CODE)
	JOIN	FACULTY f			ON (cs.INSTRUCTOR_ID 	=	f.EMPLOYEE_ID)
   WHERE	f.FIRSTNAME = 'Marie' AND f.SURNAME = 'Curie';

-- Script 7
SELECT		s.SURNAME AS StudentSurname, s.FIRSTNAME AS StudentFirstname, c.COURSE_TITLE
	FROM	STUDENT s
	JOIN	COURSE_REGISTRATION cr	ON	(s.STUDENT_ID 		= cr.STUDENT_ID)
	JOIN	CLASS_SECTION cs		ON	(cr.COURSE_CODE 		= cs.COURSE_CODE)
	JOIN	COURSE c				ON	(cs.COURSE_CODE 	= c.COURSE_CODE)
	JOIN	FACULTY f				ON	(cs.INSTRUCTOR_ID 	= f.EMPLOYEE_ID)
   WHERE	f.FIRSTNAME = 'Marie' 
	 AND f.SURNAME 		= 'Curie';

-- Script 8
SELECT		s.SURNAME AS StudentSurname, s.FIRSTNAME AS StudentFirstname, c.COURSE_TITLE
	FROM	STUDENT s, CLASS_SECTION cs, COURSE_REGISTRATION cr, COURSE c, FACULTY f
   WHERE	s.STUDENT_ID 		= cr.STUDENT_ID
	 AND	cr.COURSE_CODE 		= cs.COURSE_CODE
	 AND	cs.COURSE_CODE 		= c.COURSE_CODE
	 AND	cs.INSTRUCTOR_ID 	= f.EMPLOYEE_ID
	 AND	f.FIRSTNAME			= 'Marie'
	 AND	f.SURNAME			= 'Curie';

-- Script 9
SELECT		s.SURNAME AS StudentSurname, s.FIRSTNAME AS StudentFirstname, cs.COURSE_CODE
	FROM	STUDENT s
	JOIN	COURSE_REGISTRATION cr	ON	(s.STUDENT_ID = cr.STUDENT_ID)
	JOIN	CLASS_SECTION cs		ON	(cr.COURSE_CODE = cs.COURSE_CODE)
   WHERE	cr.GRADE IS NULL;

-- Script 10
SELECT		f.SURNAME, f.FIRSTNAME, cs.COURSE_CODE, e.EXPERTISE_LEVEL
		 FROM	FACULTY f
	LEFT JOIN	EXPERTISE e			ON	(f.EMPLOYEE_ID		= e.EMPLOYEE_ID)
	LEFT JOIN	CLASS_SECTION cs	ON	(e.COURSE_CODE		= cs.COURSE_CODE);


